[package]
name = "fitting"
version = "0.1.0"
edition = "2024"

[dependencies]

intermediate-representation = { path = "../intermediate-representation/", default-features = false, features = ["f64"]}

